CREATE TABLE USERS (
USER_ID VARCHAR(20),
PASSWORD VARCHAR(20) NOT NULL,
TIME_STAMP VARCHAR(30) NOT NULL,
PRIMARY KEY (USER_ID)
);

CREATE TABLE POSTS (
POST_ID VARCHAR(36),
USER_ID VARCHAR(20),
CONTENT VARCHAR(256) NOT NULL,
TIME_STAMP VARCHAR(30) NOT NULL,
PRIMARY KEY (POST_ID),
FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);